name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-template: "$COMPLETE"

template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: "🚀 Features"
    labels:
      - "topic"
  - title: "🐛 Bug Fixes"
    labels:
      - "bug"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

prerelease: true
prerelease-identifier: "rc"

autolabeler:
  # feature
  - label: topic
    branch:
      - "/^topic[/-].+/"

  # bug
  - label: bug
    branch:
      - "/^bugfix[/-].+/"
      - "/^hotfix[/-].+/"
